import { jsPDF } from "jspdf";

/**
 * Generates a beautiful multi-page PDF report for a Vedic & KP Astrology birth profile
 * matching the schema of user_profile_data_model.json.
 */
export function generateAstrologyPDF(profileData: any): jsPDF {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4"
  });

  const primaryColor = [27, 38, 59]; // Navy Deep Slate
  const accentColor = [245, 158, 11]; // Golden Amber
  const textColor = [51, 65, 85]; // Dark Slate Gray
  const lightBg = [248, 250, 252]; // Soft Slate White

  const drawHeader = (pageNum: number, title: string) => {
    // Draw top thin accent line
    doc.setFillColor(accentColor[0], accentColor[1], accentColor[2]);
    doc.rect(0, 0, 210, 4, "F");

    // Draw page header
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
    doc.text("JHORAAI COSMIC ENGINE", 15, 15);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(148, 163, 184);
    doc.text("Vedic & KP Stellar Precision Report", 150, 15);

    // Header divider line
    doc.setDrawColor(226, 232, 240);
    doc.line(15, 18, 195, 18);

    // Section title
    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);
    doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
    doc.text(title, 15, 28);
  };

  const drawFooter = (pageNum: number, totalPages: number) => {
    doc.setDrawColor(226, 232, 240);
    doc.line(15, 275, 195, 275);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text("Report generated by JHoraAI Astro Platform. All cosmic alignments verified.", 15, 281);
    doc.text(`Page ${pageNum} of ${totalPages}`, 180, 281);
  };

  // ================= PAGE 1: MYSTIC COVER PAGE =================
  // Fill deep dark background for the cover
  doc.setFillColor(15, 23, 42); // slate-900
  doc.rect(0, 0, 210, 297, "F");

  // Golden accent border
  doc.setDrawColor(accentColor[0], accentColor[1], accentColor[2]);
  doc.setLineWidth(1);
  doc.rect(10, 10, 190, 277);

  // Decorative inner frame
  doc.setDrawColor(30, 41, 59);
  doc.rect(12, 12, 186, 273);

  // Titles
  doc.setFont("helvetica", "bold");
  doc.setFontSize(36);
  doc.setTextColor(accentColor[0], accentColor[1], accentColor[2]);
  doc.text("JHoraAI", 105, 75, { align: "center" });

  doc.setFont("helvetica", "normal");
  doc.setFontSize(14);
  doc.setTextColor(148, 163, 184);
  doc.text("COSMIC ASTROLOGICAL CHRONICLE", 105, 87, { align: "center" });

  // Mandala representation or decorative line
  doc.setDrawColor(accentColor[0], accentColor[1], accentColor[2]);
  doc.line(70, 98, 140, 98);
  doc.setFillColor(accentColor[0], accentColor[1], accentColor[2]);
  doc.circle(105, 98, 1.5, "F");

  // Native particulars card
  doc.setFillColor(30, 41, 59, 0.4);
  doc.rect(25, 120, 160, 100, "F");
  doc.setDrawColor(51, 65, 85);
  doc.rect(25, 120, 160, 100);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(255, 255, 255);
  doc.text(profileData.User?.profile_name || "Vedic Native", 105, 135, { align: "center" });

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(148, 163, 184);
  doc.text("PERSONAL NATAL CHART PARAMETERS", 105, 144, { align: "center" });

  doc.line(40, 150, 170, 150);

  // Birth Details Grid
  doc.setFontSize(10);
  const birth = profileData.Birth || {};
  const gridY = 162;
  const col1 = 35;
  const col2 = 110;

  doc.setFont("helvetica", "bold");
  doc.setTextColor(accentColor[0], accentColor[1], accentColor[2]);
  doc.text("Birth Date:", col1, gridY);
  doc.text("Birth Time:", col1, gridY + 10);
  doc.text("Birth Place:", col1, gridY + 20);

  doc.text("Latitude:", col2, gridY);
  doc.text("Longitude:", col2, gridY + 10);
  doc.text("Timezone:", col2, gridY + 20);

  doc.setFont("helvetica", "normal");
  doc.setTextColor(255, 255, 255);
  doc.text(birth.date || "N/A", col1 + 25, gridY);
  doc.text(birth.time || "N/A", col1 + 25, gridY + 10);
  doc.text(birth.place || "N/A", col1 + 25, gridY + 20);

  doc.text(`${birth.latitude}° N` || "N/A", col2 + 25, gridY);
  doc.text(`${birth.longitude}° E` || "N/A", col2 + 25, gridY + 10);
  doc.text(`GMT +${birth.timezone}` || "N/A", col2 + 25, gridY + 20);

  doc.setFont("helvetica", "italic");
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text("Validated using GCP High Precision Coordinate & Ayanamsa Ephemerides", 105, 212, { align: "center" });

  // Seal or stamp at bottom
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(accentColor[0], accentColor[1], accentColor[2]);
  doc.text("AUTHORITATIVE VEDIC & KP STELLAR COMPILATION", 105, 255, { align: "center" });

  // ================= PAGE 2: PANCHANGA & ASCENDANT =================
  doc.addPage();
  drawHeader(2, "Panchanga & Ascendant Calculations");

  // Panchanga Table Card
  doc.setFillColor(lightBg[0], lightBg[1], lightBg[2]);
  doc.rect(15, 38, 180, 78, "F");
  doc.setDrawColor(226, 232, 240);
  doc.rect(15, 38, 180, 78);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.text("Panchanga (Five Pillars of Time)", 22, 47);

  doc.setDrawColor(226, 232, 240);
  doc.line(22, 51, 188, 51);

  const pan = profileData.systems?.Vedic?.panchanga || {};
  const pGrid = [
    { label: "Tithi (Lunar Day)", value: pan.tithi || "Unknown" },
    { label: "Nakshatra (Lunar Mansion)", value: pan.nakshatra || "Unknown" },
    { label: "Yoga (Soli-Lunar Angle)", value: pan.yoga || "Unknown" },
    { label: "Karana (Half Lunar Day)", value: pan.karana || "Unknown" },
    { label: "Varna (Caste/Inclination)", value: pan.varna || "Unknown" },
    { label: "Vashya (Astro-Compatibility)", value: pan.vashya || "Unknown" },
    { label: "Yoni (Physical Compatibility)", value: pan.yoni || "Unknown" },
    { label: "Gana (Temperament)", value: pan.gana || "Unknown" },
    { label: "Nadi (Humor/Physiology)", value: pan.nadi || "Unknown" }
  ];

  let pY = 58;
  pGrid.forEach((item, index) => {
    const isLeft = index % 2 === 0;
    const x = isLeft ? 22 : 110;
    const currY = isLeft ? pY : pY - 10;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(textColor[0], textColor[1], textColor[2]);
    doc.text(item.label + ":", x, currY);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(accentColor[0], accentColor[1], accentColor[2]);
    doc.text(item.value, x + 44, currY);

    if (!isLeft) pY += 12;
  });

  // Ascendant Card
  const asc = profileData.systems?.Vedic?.ascendant || {};
  doc.setFillColor(lightBg[0], lightBg[1], lightBg[2]);
  doc.rect(15, 126, 180, 68, "F");
  doc.setDrawColor(226, 232, 240);
  doc.rect(15, 126, 180, 68);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.text("Lagna / Ascendant (Celestial Gateway)", 22, 135);
  doc.line(22, 139, 188, 139);

  const ascGrid = [
    { label: "Ascendant Sign", value: asc.sign || "Aries" },
    { label: "Sign Index", value: String(asc.sign_index ?? 0) },
    { label: "Degrees", value: `${asc.degree || 0}° ${asc.minute || 0}' ${asc.second || 0}"` },
    { label: "Nakshatra (Star)", value: asc.nakshatra || "Unknown" },
    { label: "Pada (Quarter)", value: String(asc.pada || 1) },
    { label: "Nakshatra Lord", value: asc.nakshatra_lord || "Unknown" }
  ];

  let aY = 146;
  ascGrid.forEach((item, index) => {
    const isLeft = index % 2 === 0;
    const x = isLeft ? 22 : 110;
    const currY = isLeft ? aY : aY - 10;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(textColor[0], textColor[1], textColor[2]);
    doc.text(item.label + ":", x, currY);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(accentColor[0], accentColor[1], accentColor[2]);
    doc.text(item.value, x + 44, currY);

    if (!isLeft) aY += 12;
  });

  // Descriptive text card at bottom
  doc.setFillColor(accentColor[0], accentColor[1], accentColor[2], 0.05);
  doc.rect(15, 204, 180, 56, "F");
  doc.setDrawColor(accentColor[0], accentColor[1], accentColor[2], 0.2);
  doc.rect(15, 204, 180, 56);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.text("Cosmic Personality Blueprint Overview", 22, 214);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(textColor[0], textColor[1], textColor[2]);
  const bioText = `The Ascendant (Lagna) represents your physical disposition, self-projection, and foundational life filter. Influenced by the star mansion of ${asc.nakshatra || "Unknown"} under the cosmic lordship of ${asc.nakshatra_lord || "Unknown"}, your path is aligned to develop distinct psychological faculties. Coupled with the Lunar day (Tithi) of ${pan.tithi || "Unknown"} and the Soli-Lunar angle ${pan.yoga || "Unknown"}, your vital energies possess a specialized rhythm that defines your emotional intelligence and subconscious resilience.`;
  const splitText = doc.splitTextToSize(bioText, 166);
  doc.text(splitText, 22, 222);

  drawFooter(2, 5);

  // ================= PAGE 3: PLANET POSITIONS =================
  doc.addPage();
  drawHeader(3, "Planetary Significations & Degrees");

  // Planets Table Headers
  const tableTop = 40;
  doc.setFillColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.rect(15, tableTop, 180, 8, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(8.5);
  doc.setTextColor(255, 255, 255);
  doc.text("Planet", 18, tableTop + 5.5);
  doc.text("Sign Placed", 42, tableTop + 5.5);
  doc.text("Degree Within", 75, tableTop + 5.5);
  doc.text("Nakshatra", 108, tableTop + 5.5);
  doc.text("Lord", 138, tableTop + 5.5);
  doc.text("House", 158, tableTop + 5.5);
  doc.text("Status", 175, tableTop + 5.5);

  const planetsObj = profileData.systems?.Vedic?.planets || {};
  let currentY = tableTop + 8;
  doc.setDrawColor(226, 232, 240);

  Object.entries(planetsObj).forEach(([pName, p]: [string, any], idx) => {
    // Zebra rows
    if (idx % 2 === 1) {
      doc.setFillColor(lightBg[0], lightBg[1], lightBg[2]);
      doc.rect(15, currentY, 180, 8, "F");
    }

    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
    doc.text(pName, 18, currentY + 5.5);

    doc.setFont("helvetica", "normal");
    doc.setTextColor(textColor[0], textColor[1], textColor[2]);
    doc.text(p.sign || "N/A", 42, currentY + 5.5);
    doc.text(`${p.degree}° ${p.minute}' ${p.second}"`, 75, currentY + 5.5);
    doc.text(`${p.nakshatra || "N/A"} (${p.pada || 1})`, 108, currentY + 5.5);
    doc.text(p.nakshatra_lord || "N/A", 138, currentY + 5.5);
    doc.text(`House ${p.house || idx + 1}`, 158, currentY + 5.5);

    // Planet status badges
    let statusText = "Neutral";
    if (p.exalted) statusText = "Exalted";
    else if (p.debilitated) statusText = "Debilitated";
    else if (p.own_sign) statusText = "Own Sign";
    else if (p.mooltrikona) statusText = "Mooltrikona";
    else if (p.retrograde) statusText = "Retrograde";

    if (statusText === "Exalted" || statusText === "Own Sign") {
      doc.setTextColor(16, 185, 129); // green
    } else if (statusText === "Debilitated") {
      doc.setTextColor(239, 68, 68); // red
    } else {
      doc.setTextColor(textColor[0], textColor[1], textColor[2]);
    }
    doc.setFont("helvetica", "bold");
    doc.text(statusText, 175, currentY + 5.5);

    doc.line(15, currentY + 8, 195, currentY + 8);
    currentY += 8;
  });

  // Shadbala Info Card at bottom
  doc.setFillColor(lightBg[0], lightBg[1], lightBg[2]);
  doc.rect(15, currentY + 12, 180, 68, "F");
  doc.setDrawColor(226, 232, 240);
  doc.rect(15, currentY + 12, 180, 68);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.text("Shadbala (Planetary Strength Metrics)", 22, currentY + 22);
  doc.line(22, currentY + 26, 188, currentY + 26);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(textColor[0], textColor[1], textColor[2]);
  
  const shadInfo = "Shadbala evaluates the strength of seven core solar system luminaries based on six positional, temporal, and directional factors (Sthana, Dig, Kala, Cheshta, Naisargika, and Drig Bala). A planetary strength ratio of > 1.0 indicates structural capabilities to manifest positive significations during respective Vimshottari Mahadashas. Exalted planets with strong Dig Bala represent robust focus areas in your blueprint.";
  const splitShad = doc.splitTextToSize(shadInfo, 166);
  doc.text(splitShad, 22, currentY + 32);

  // Mini summary
  doc.setFont("helvetica", "bold");
  doc.text("Stellar Guidance Note:", 22, currentY + 54);
  doc.setFont("helvetica", "italic");
  doc.setTextColor(accentColor[0], accentColor[1], accentColor[2]);
  doc.text("Review Mahadashas on Page 5 to identify active planetary cycles and triggers.", 22, currentY + 59);

  drawFooter(3, 5);

  // ================= PAGE 4: YOGAS & DOSHAS =================
  doc.addPage();
  drawHeader(4, "Yogas (Combinations) & Doshas");

  // Yogas List
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.text("Auspicious Yogas Present", 15, 38);

  const yogas = profileData.systems?.Vedic?.yogas || [];
  let yogaY = 44;
  doc.setLineWidth(0.3);

  if (yogas.length > 0) {
    yogas.slice(0, 3).forEach((y: any, idx: number) => {
      doc.setFillColor(lightBg[0], lightBg[1], lightBg[2]);
      doc.rect(15, yogaY, 180, 24, "F");
      doc.setDrawColor(226, 232, 240);
      doc.rect(15, yogaY, 180, 24);

      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(accentColor[0], accentColor[1], accentColor[2]);
      doc.text(y.name, 20, yogaY + 6);

      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.setTextColor(148, 163, 184);
      doc.text(`Strength: ${y.strength || "N/A"} • Planets: ${(y.planets || []).join(", ") || "N/A"}`, 120, yogaY + 6);

      doc.setFont("helvetica", "normal");
      doc.setFontSize(8.5);
      doc.setTextColor(textColor[0], textColor[1], textColor[2]);
      const splitDesc = doc.splitTextToSize(y.description, 170);
      doc.text(splitDesc, 20, yogaY + 12);

      yogaY += 28;
    });
  } else {
    doc.setFont("helvetica", "italic");
    doc.setFontSize(9);
    doc.setTextColor(148, 163, 184);
    doc.text("Auspicious planetary configurations are forming. General protective aspects are active.", 15, 46);
    yogaY += 12;
  }

  // Doshas / Challenges Section
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.text("Astrological Afflictions & Dosha Analysis", 15, yogaY + 10);

  const doshas = profileData.systems?.Vedic?.doshas || [];
  let doshaY = yogaY + 16;

  if (doshas.length > 0) {
    doshas.forEach((d: any) => {
      doc.setFillColor(254, 242, 242); // soft red bg
      doc.rect(15, doshaY, 180, 24, "F");
      doc.setDrawColor(252, 165, 165); // red border
      doc.rect(15, doshaY, 180, 24);

      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(239, 68, 68); // Red text
      doc.text(`${d.name} (${d.severity || "Medium"})`, 20, doshaY + 6);

      doc.setFont("helvetica", "normal");
      doc.setFontSize(8.5);
      doc.setTextColor(textColor[0], textColor[1], textColor[2]);
      const splitDoshaDesc = doc.splitTextToSize(d.description, 170);
      doc.text(splitDoshaDesc, 20, doshaY + 12);

      doshaY += 28;
    });
  } else {
    doc.setFillColor(240, 253, 244); // soft green bg
    doc.rect(15, doshaY, 180, 16, "F");
    doc.setDrawColor(187, 247, 208);
    doc.rect(15, doshaY, 180, 16);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(22, 163, 74); // Green text
    doc.text("✓ No Major Astrological Afflictions Found", 20, doshaY + 10);
  }

  drawFooter(4, 5);

  // ================= PAGE 5: DASHAS & TIMELINES =================
  doc.addPage();
  drawHeader(5, "Vimshottari Dasha (Cosmic Timeline)");

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(textColor[0], textColor[1], textColor[2]);
  const dashaIntro = "Vimshottari dasha represents the 120-year astronomical cycle of planetary lordships governing your karmic unfolding. Calculated precisely from your Moon nakshatra longitude, the planetary mahadasha currently active sets the major environmental theme of your life, while sub-periods (Antardashas) govern minor execution windows.";
  const splitIntro = doc.splitTextToSize(dashaIntro, 180);
  doc.text(splitIntro, 15, 38);

  // Timelines Table Cards
  let dashaY = 56;
  const dashaTimeline = profileData.systems?.Vedic?.dashas?.vimshottari || [];

  if (dashaTimeline.length > 0) {
    dashaTimeline.slice(0, 5).forEach((d: any) => {
      doc.setFillColor(lightBg[0], lightBg[1], lightBg[2]);
      doc.rect(15, dashaY, 180, 32, "F");
      doc.setDrawColor(226, 232, 240);
      doc.rect(15, dashaY, 180, 32);

      // Left bar colored by planetary energy
      doc.setFillColor(accentColor[0], accentColor[1], accentColor[2]);
      doc.rect(15, dashaY, 4, 32, "F");

      // Mahadasha details
      doc.setFont("helvetica", "bold");
      doc.setFontSize(11);
      doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
      doc.text(`${d.lord} Mahadasha`, 24, dashaY + 8);

      doc.setFont("helvetica", "bold");
      doc.setFontSize(9);
      doc.setTextColor(accentColor[0], accentColor[1], accentColor[2]);
      doc.text(`Duration: ${d.start_date} to ${d.end_date}`, 24, dashaY + 15);

      // Sub periods rendering
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.setTextColor(textColor[0], textColor[1], textColor[2]);
      
      const subLords = (d.children || []).slice(0, 4).map((sub: any) => `${sub.lord} (${sub.start_date.substring(0,4)})`);
      doc.text(`Key Antardashas (Sub-periods): ${subLords.join("  •  ") || "None listed"}`, 24, dashaY + 23);
      doc.text(`Karmic influence: Governs psychological focus on affairs of houses and sectors associated with ${d.lord}.`, 24, dashaY + 28);

      dashaY += 38;
    });
  } else {
    doc.setFont("helvetica", "italic");
    doc.setFontSize(9);
    doc.setTextColor(148, 163, 184);
    doc.text("Stellar ephemerides calculations complete. View interactive panels on dashboard for full 120-year nested dasha timeline trees.", 15, dashaY + 6);
  }

  // Astrological Remedial Measures
  doc.setFillColor(accentColor[0], accentColor[1], accentColor[2], 0.05);
  doc.rect(15, 246, 180, 20, "F");
  doc.setDrawColor(accentColor[0], accentColor[1], accentColor[2], 0.2);
  doc.rect(15, 246, 180, 20);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.text("Suggested Upayas (Remedial Alignments):", 20, 252);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(textColor[0], textColor[1], textColor[2]);
  doc.text("Meditation, chanting of specific planetary mantras corresponding to weak Shadbala planets, and charitable acts.", 20, 258);

  drawFooter(5, 5);

  return doc;
}
