import React, { useState } from "react";
import { Sliders, HelpCircle, Compass, History, Settings, Sparkles, SidebarOpen, SidebarClose, UserCheck, Menu, Download } from "lucide-react";
import { useConversation } from "../features/ask/hooks/useConversation";
import { useBirthProfiles } from "../features/ask/hooks/useBirthProfiles";
import { ConversationHistory } from "../features/ask/components/ConversationHistory";
import { SavedCharts } from "../features/ask/components/SavedCharts";
import { TimelinePanel } from "../features/ask/components/TimelinePanel";
import { ConversationPanel } from "../features/ask/components/ConversationPanel";
import { CurrentSkyPanel } from "../features/ask/components/CurrentSkyPanel";
import { ProviderSettings } from "../features/ask/components/ProviderSettings";

export default function AskWorkspace() {
  const {
    conversations,
    activeConversation,
    preferences,
    isGenerating,
    pendingProfile,
    updatePreferences,
    selectConversation,
    startNewConversation,
    deleteConversation,
    sendMessage,
    retryLastMessage,
    abortGeneration,
    confirmPendingProfile,
    cancelPendingProfile,
  } = useConversation();

  const {
    profiles,
    activeProfile,
    selectProfile,
    addProfile,
    deleteProfile,
  } = useBirthProfiles();

  const [activeTab, setActiveTab] = useState<"chat" | "charts" | "timeline" | "settings">("chat");
  const [showLeftSidebar, setShowLeftSidebar] = useState(false);
  const [showRightSidebar, setShowRightSidebar] = useState(false);
  const [developerMode, setDeveloperMode] = useState(false);

  const exportConversation = () => {
    if (!activeConversation) return;
    const title = activeConversation.title || "Astrological Consultation";
    const profileText = activeProfile 
      ? `Birth Profile: ${activeProfile.name} (${activeProfile.date} ${activeProfile.time}, ${activeProfile.place})\n` +
        `Coordinates: Lat ${activeProfile.latitude}°N, Lng ${activeProfile.longitude}°E\n\n`
      : "";
    
    let text = `# ${title}\n`;
    text += `Generated by JHoraAI Professional Consultation\n`;
    text += `Date: ${new Date().toLocaleDateString()}\n`;
    text += `==================================================\n\n`;
    text += profileText;

    activeConversation.messages.forEach((msg) => {
      const role = msg.role === "user" ? "Client" : "JHoraAI Professional Astrologer";
      text += `### [${role}]\n${msg.content}\n\n`;
      text += `--------------------------------------------------\n\n`;
    });

    const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `${title.toLowerCase().replace(/\s+/g, "_")}_transcript.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="bg-slate-50 text-slate-800 rounded-3xl border border-slate-200/80 shadow-md overflow-hidden h-[780px] flex flex-col md:flex-row transition-all duration-300 text-left">
      {/* LEFT SIDEBAR - Navigation & Library */}
      {showLeftSidebar && (
        <aside className="w-full md:w-64 shrink-0 bg-white border-r border-slate-150 flex flex-col h-full">
        {/* Left Sidebar header */}
        <div className="p-4 border-b border-slate-100 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Sparkles className="w-4 h-4 text-blue-600" />
            <span className="font-sans font-bold text-xs uppercase tracking-wider text-slate-800">
              JHoraAI Pro Workspace
            </span>
          </div>
          <button
            onClick={() => setActiveTab(activeTab === "settings" ? "chat" : "settings")}
            className={`p-1.5 rounded-lg border transition-all cursor-pointer ${
              activeTab === "settings"
                ? "bg-blue-50 border-blue-200 text-blue-600"
                : "bg-slate-50 border-slate-200 text-slate-500 hover:bg-slate-100"
            }`}
            title="Intelligence Settings"
          >
            <Settings className="w-3.5 h-3.5" />
          </button>
        </div>

        {/* Tab switchers */}
        <div className="p-3 grid grid-cols-3 gap-1 border-b border-slate-100 bg-slate-50/50">
          {(["chat", "charts", "timeline"] as const).map((tab) => (
            <button
              key={tab}
              onClick={() => {
                setActiveTab(tab);
              }}
              className={`py-1.5 rounded-lg text-[10px] font-bold uppercase tracking-wider transition-all cursor-pointer ${
                activeTab === tab
                  ? "bg-white text-slate-800 shadow-sm border border-slate-200/80 font-extrabold"
                  : "text-slate-400 hover:text-slate-600 hover:bg-slate-100"
              }`}
            >
              {tab}
            </button>
          ))}
        </div>

        {/* Dynamic Left sidebar viewport scroll */}
        <div className="flex-1 overflow-y-auto p-4 space-y-5">
          {activeTab === "chat" && (
            <ConversationHistory
              conversations={conversations}
              activeId={activeConversation?.id}
              onSelect={selectConversation}
              onDelete={deleteConversation}
              onNew={startNewConversation}
            />
          )}

          {activeTab === "charts" && (
            <SavedCharts
              profiles={profiles}
              activeProfile={activeProfile}
              onSelectProfile={selectProfile}
              onAddProfile={addProfile}
              onDeleteProfile={deleteProfile}
            />
          )}

          {activeTab === "timeline" && <TimelinePanel />}

          {activeTab === "settings" && (
            <div className="text-left text-xs text-slate-400 space-y-3">
              <span className="font-bold uppercase tracking-wider text-[10px]">Quick Access</span>
              <p>Configure keys or preferred LLM engines in the center panel settings card.</p>
              <button
                onClick={() => setActiveTab("chat")}
                className="text-blue-600 font-bold hover:underline cursor-pointer"
              >
                Return to chat
              </button>
            </div>
          )}
        </div>

        {/* Left Sidebar footer / status indicator */}
        <div className="p-3 border-t border-slate-100 bg-slate-50/30 flex items-center justify-between text-[10px] text-slate-400">
          <div className="flex items-center gap-1.5">
            <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-pulse" />
            <span>AI Coprocessor Live</span>
          </div>
          <span className="text-slate-300 font-mono">v1.2</span>
        </div>
      </aside>
      )}

      {/* CENTER WORKSPACE - Conversation Area */}
      <main className="flex-1 flex flex-col h-full bg-white relative border-r border-slate-150">
        {/* Workspace Center Header bar */}
        <div className="h-14 px-6 border-b border-slate-100 flex items-center justify-between shrink-0 bg-white/95">
          <div className="flex items-center gap-3">
            <button
              onClick={() => setShowLeftSidebar(!showLeftSidebar)}
              className={`p-1.5 rounded-lg border transition-all cursor-pointer ${
                showLeftSidebar
                  ? "bg-slate-100 text-slate-700 border-slate-200"
                  : "bg-white text-slate-400 border-slate-150 hover:bg-slate-50"
              }`}
              title="Toggle Consultation Library / History"
            >
              <Menu className="w-4 h-4" />
            </button>
            <h2 className="font-sans font-bold text-slate-800 text-sm">
              {activeTab === "settings" ? "Intelligence Configuration" : "Interactive Copilot Thread"}
            </h2>
            {activeProfile && (
              <span className="flex items-center gap-1 text-[10px] bg-blue-50 text-blue-700 px-2 py-0.5 rounded-full border border-blue-100/50 font-semibold font-sans">
                <UserCheck className="w-3 h-3" />
                Aligned: {activeProfile.name}
              </span>
            )}
          </div>

          <div className="flex items-center gap-2">
            {activeConversation && activeConversation.messages.length > 0 && (
              <button
                onClick={exportConversation}
                className="p-1.5 rounded-lg border bg-white border-slate-150 text-slate-500 hover:text-slate-700 hover:bg-slate-50 transition-all flex items-center gap-1 cursor-pointer text-[11px] font-semibold"
                title="Export Consultation Transcript"
              >
                <Download className="w-3.5 h-3.5" />
                <span className="hidden sm:inline">Export</span>
              </button>
            )}

            <button
              onClick={() => setDeveloperMode(!developerMode)}
              className={`p-1.5 rounded-lg border transition-all flex items-center gap-1.5 cursor-pointer text-[11px] font-semibold ${
                developerMode
                  ? "bg-amber-50 border-amber-200 text-amber-700"
                  : "bg-white border-slate-150 text-slate-400 hover:bg-slate-50 hover:text-slate-600"
              }`}
              title="Toggle Developer Diagnostics / Reasoning Pipeline"
            >
              <Sliders className="w-3.5 h-3.5" />
              <span className="hidden sm:inline">Dev Mode</span>
              <span className={`w-1.5 h-1.5 rounded-full ${developerMode ? "bg-amber-500 animate-pulse" : "bg-slate-300"}`} />
            </button>

            <button
              onClick={() => setShowRightSidebar(!showRightSidebar)}
              className={`p-1.5 rounded-lg border transition-all cursor-pointer ${
                showRightSidebar
                  ? "bg-slate-100 text-slate-700 border-slate-200"
                  : "bg-white text-slate-400 border-slate-150 hover:bg-slate-50"
              }`}
              title="Toggle Transit Sky Sidebar"
            >
              {showRightSidebar ? (
                <SidebarClose className="w-4 h-4" />
              ) : (
                <SidebarOpen className="w-4 h-4" />
              )}
            </button>
          </div>
        </div>

        <div className="flex-1 relative overflow-hidden bg-white">
          {activeTab === "settings" ? (
            <div className="h-full overflow-y-auto px-4 py-6">
              <ProviderSettings
                preferences={preferences}
                onSave={(updated) => {
                  updatePreferences(updated);
                  setActiveTab("chat");
                }}
              />
            </div>
          ) : (
            <ConversationPanel
              conversation={activeConversation}
              isGenerating={isGenerating}
              pendingProfile={pendingProfile}
              developerMode={developerMode}
              exportConversation={exportConversation}
              onSendMessage={(text) => sendMessage(text, activeProfile)}
              onRetry={retryLastMessage}
              onStop={abortGeneration}
              onConfirmProfile={(prof) => {
                confirmPendingProfile(prof);
                selectProfile(prof); // Align chart
              }}
              onCancelProfile={cancelPendingProfile}
            />
          )}
        </div>
      </main>

      {/* RIGHT SIDEBAR - Transits / Sky Placements */}
      {showRightSidebar && (
        <aside className="w-full md:w-64 shrink-0 bg-white flex flex-col h-full">
          {/* Right Sidebar header */}
          <div className="p-4 border-b border-slate-100 flex items-center justify-between">
            <div className="flex items-center gap-1.5">
              <Compass className="w-4 h-4 text-amber-500" />
              <span className="font-sans font-bold text-xs uppercase tracking-wider text-slate-800">
                Aligned Sky Coordinates
              </span>
            </div>
          </div>

          {/* Right Sidebar scroll area */}
          <div className="flex-1 overflow-y-auto p-4">
            <CurrentSkyPanel activeProfile={activeProfile} />
          </div>
        </aside>
      )}
    </div>
  );
}
